import {
  IconActivity,
  IconAlertTriangle,
  IconArrowRight,
  IconBrandGithub,
  IconBrandTwitter,
  IconChartBar,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconClock,
  IconCommand,
  IconCpu,
  IconCreditCard,
  IconDeviceDesktop,
  IconDeviceLaptop,
  IconDotsVertical,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLoader2,
  IconLogin,
  IconMoon,
  IconNetwork,
  IconPhoto,
  IconPizza,
  IconPlus,
  IconProps,
  IconServer,
  IconSettings,
  IconShoppingBag,
  IconSun,
  IconTrash,
  IconTrendingUp,
  IconTrendingDown,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  activity: IconActivity,
  chartBar: IconChartBar,
  cpu: IconCpu,
  desktop: IconDeviceDesktop,
  network: IconNetwork,
  server: IconServer,
  trendingUp: IconTrendingUp,
  trendingDown: IconTrendingDown,
  photo: IconPhoto,
  clock: IconClock
};
